### ISSUE TITLE
format Spring 2015 NCWIT application nicely

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/awards-grants#1]
We should have a link on the CS Women webpage that has successful award/grant applications.

**Comment by strubell** [comment]
On a related note, the application that's currently in here is definitely a draft, can we get the final writeup on here? I think I have it somewhere (google docs? email?) but am unable to find it...

**Comment by etosch** [comment]
I believe this is actually the closest thing we have to the final copy 
-- I copied and pasted from here into the NCWIT form (we did not upload 
things). Any changes I made between the Google doc and here are 
basically lost at sea (since they don't send us what we wrote). We might 
be able to ask them for a dump of this.

On 10/26/15 3:35 PM, Emma Strubell wrote:

> On a related note, the application that's currently in here is 
> definitely a draft, can we get the final writeup on here? I think I 
> have it somewhere (google docs? email?) but am unable to find it...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/CSWomenUMass/awards-grants/issues/1#issuecomment-151260139.

## 

Emma Tosch
PhD Candidate, College of Information & Computer Sciences
University of Massachusetts Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by strubell** [comment]
My bad, I didn't realize the doc had really long lines and when skimming I interpreted it as all notes -- what's here is good and definitely seems close enough to the final version (if not equivalent)
